model:
  gaussian_width: 0.8
  nfeat_bond: 1000
  cutoff: 5.0
  epochs: 1000
  batch_size: 64
  lr: 2.0e-3
  losses: 'MSE'
#    - 'MAE'
#    - 'MSE'
  preload_embeddings: # None
  clipnorm: 0.8
data:
  path: '../data/dichalcogenides_public'
  train_val_ratio: 0.1
  random_state: 123456
