model:
  gaussian_width: 0.8
  nfeat_bond: 1000
  cutoff: 5.0
  epochs: 1000
  batch_size: 64
  lr: 2.0e-3
  losses: 'lambda y_true, y_pred: keras.losses.mean_squared_error(y_true, y_pred) + keras.losses.mean_absolute_error(y_true, y_pred)'
#    - 'MAE'
#    - 'MSE'
  preload_embeddings: './mvl_models/mf_2020/pbe_gllb_hse_exp_disorder/0/best_model.hdf5'# None
  clipnorm: 0.8
data:
  path: '../data/dichalcogenides_public'
  train_val_ratio: 0.1
  random_state: 123456
